---
- name: Show interfaces
  hosts: vyos
  gather_facts: false

  tasks:

    # Example from Ansible Playbooks
    - script: ./sh_interfaces.sh
      register: sh_result

    - debug: var=sh_result.stdout_lines


